In [2]:
import pennylane as qml
import numpy as np

In [7]:
state=np.array([0.5, np.sqrt(3)/2*1j])
U=np.array([[1/np.sqrt(2), (1/np.sqrt(2))*1j], [1/np.sqrt(2), (-1/np.sqrt(2))*1j]])

In [161]:
alpha = 1+1j
beta = 1-1j

amplitude = np.array([alpha, beta], dtype=complex)
norm = np.sqrt(np.sum(np.abs(amplitude)**2))
normalized = amplitude / norm
normalized

array([0.5+0.5j, 0.5-0.5j])

In [167]:
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])
np.conj(np.transpose(ket_0))@ket_1

0

In [233]:
num_meas=10
state = np.array([0.8, 0.6])
c=np.round(num_meas*(np.abs(state)**2)[0])
np.random.choice(2,num_meas,p=np.abs(state)**2)

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 1])

In [238]:
dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def apply_rx_pi(state):

    if state == 1:
        qml.PauliX(wires=0)

    qml.RX(np.pi, wires=0)

    return qml.state()


print(apply_rx_pi(0))
print(apply_rx_pi(1))

[6.123234e-17+0.j 0.000000e+00-1.j]
[0.000000e+00-1.j 6.123234e-17+0.j]


In [130]:
state=np.array([0.5, complex(0,np.sqrt(3)/2)])
state=state/np.linalg.norm(state)
U=np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [complex(0,1/np.sqrt(2)), complex(0,-1/np.sqrt(2))]])
dev = qml.device("default.qubit", wires=1)
@qml.qnode(dev)
def op():
    qml.StatePrep(state, wires=0)
    qml.QubitUnitary(U, wires=0)
    return qml.state()
op()

array([0.35355339+0.61237244j, 0.61237244+0.35355339j])